package ec.edu.espe.ehamanagement.view;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class PnlHelpMaterialsOrganizer extends javax.swing.JPanel {

    public PnlHelpMaterialsOrganizer() {
        initComponents();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupProducts = new javax.swing.ButtonGroup();
        btnGroupSearch = new javax.swing.ButtonGroup();
        pnlContent = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        lblContent1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblContent2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        lblContent3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTableTitle.setText("Materials Organizer");

        lblContent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent.setText("Añadir un nuevo Material");
        lblContent.setAlignmentX(0.5F);

        lblContent1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent1.setText("Acceder a Organizador de Materiales");
        lblContent1.setAlignmentX(0.5F);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Ubicarse en la barra de navegación del aplicativo \n2. Dar click en Actions \n3. De la lista de opciones dar click en Materials Organizer \n4. Podrá observar un menú con las opciones de añadir \nmaterial y retornar, una tabla que contiene los materiales \nregistrados y la opción de búsqueda. ");
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Pulsar en el primer botón del menú llamado \n“añadir material”. \n2. Se desplegará un formulario con 3 campos a \ncompletar. \n3. En el primer campo, ingrese el nombre que desee \npara el material. \n4. En el segundo campo ingrese la cantidad del material \n va a ingresar. \n5. En el tercer campo, Ingrese el costo general del \nmaterial. \n6. Finalmente pulse en el botón “Guardar” que se \nencuentra en la parte inferior derecha de la ventana. \n7. Aparecerá una alerta de confirmación para añadir el \nnuevo material, debe pulsar Ok si la información \ningresada es la deseada, caso contrario pulsar cancelar. \n8. Finalmente, si el proceso es realizado correctamente \npodrá visualizar una alerta confirmando la correcta \nrealización de la acción. ");
        jTextArea2.setFocusable(false);
        jTextArea2.setOpaque(false);
        jScrollPane3.setViewportView(jTextArea2);

        lblContent2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent2.setText("Buscar un Material");
        lblContent2.setAlignmentX(0.5F);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("1. En la opción de búsqueda que se encuentra en la parte\n inferior de la ventana del organizador de materiales, \nencontrará un campo de búsqueda y la opción \nde búsqueda por ID y por Nombre. \n2. Ingrese el tipo de búsqueda que desea realizar. \n3. En el campo de texto, ingrese el dato a buscar. \n4. Finalmente pulse en el botón de buscar, \nque se encuentra a la derecha de la sección de búsqueda.\n\n\n\n\n\n");
        jTextArea3.setFocusable(false);
        jTextArea3.setOpaque(false);
        jScrollPane4.setViewportView(jTextArea3);

        lblContent3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent3.setText("Modificar un Material");
        lblContent3.setAlignmentX(0.5F);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("1. En la opción de búsqueda que se encuentra en la parte\ninferior de la ventana del organizador de materiales, \nencontrará un campo de búsqueda y la opción de\nbúsqueda por ID y por Nombre. \n2. Ingrese el tipo de búsqueda que desea realizar. \n3. En el campo de texto, ingrese el dato a buscar. \n4. Finalmente pulse en el botón de buscar, que se \nencuentra a la derecha de la sección de búsqueda.\n");
        jTextArea4.setFocusable(false);
        jTextArea4.setOpaque(false);
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTableTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblContent1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContent, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblContent2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlContentLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContent3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContent1)
                    .addComponent(lblContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContent2)
                    .addComponent(lblContent3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupSearch;
    private javax.swing.ButtonGroup btnGrupProducts;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblContent1;
    private javax.swing.JLabel lblContent2;
    private javax.swing.JLabel lblContent3;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
