package ec.edu.espe.ehamanagement.view;

import com.mongodb.client.MongoCollection;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class PnlHelp extends javax.swing.JPanel {
    
    public PnlHelp() {
        initComponents();
        initHelpUserProfile();
    }
    private void initHelpUserProfile(){
        PnlHelpUserProfile helpUser = new PnlHelpUserProfile();
        helpUser.setSize(713,518);
        helpUser.setLocation(0,0);
        pnlContent.removeAll();
        pnlContent.add(helpUser);
        pnlContent.revalidate();
        pnlContent.repaint(); 
    }
    private void initHelpMaterialsOrganizer(){
        PnlHelpMaterialsOrganizer helpMaterials = new PnlHelpMaterialsOrganizer();
        helpMaterials.setSize(713,518);
        helpMaterials.setLocation(0,0);
        pnlContent.removeAll();
        pnlContent.add(helpMaterials);
        pnlContent.revalidate();
        pnlContent.repaint(); 
    }
    private void initPnlHelpInventory(){
        PnlHelpInventory helpInventory = new PnlHelpInventory();
        helpInventory.setSize(713,518);
        helpInventory.setLocation(0,0);
        pnlContent.removeAll();
        pnlContent.add(helpInventory);
        pnlContent.revalidate();
        pnlContent.repaint(); 
    }
    private void initPnlHelpAgenda(){
        PnlHelpAgenda helpAgenda = new PnlHelpAgenda();
        helpAgenda.setSize(713,518);
        helpAgenda.setLocation(0,0);
        pnlContent.removeAll();
        pnlContent.add(helpAgenda);
        pnlContent.revalidate();
        pnlContent.repaint(); 
    }
    
    private void initPnlHelpReports(){
        PnlHelpReports helpReports = new PnlHelpReports();
        helpReports.setSize(713,518);
        helpReports.setLocation(0,0);
        pnlContent.removeAll();
        pnlContent.add(helpReports);
        pnlContent.revalidate();
        pnlContent.repaint(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnMaterialsOrganizer = new javax.swing.JButton();
        btnUserProfile = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnInventory1 = new javax.swing.JButton();
        btnAgenda1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(17, 39, 75));
        jPanel3.setToolTipText("");

        btnMaterialsOrganizer.setBackground(new java.awt.Color(0, 153, 153));
        btnMaterialsOrganizer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMaterialsOrganizer.setForeground(new java.awt.Color(255, 255, 255));
        btnMaterialsOrganizer.setText("Materials Organizer");
        btnMaterialsOrganizer.setToolTipText("Back to Inventory Table");
        btnMaterialsOrganizer.setBorder(null);
        btnMaterialsOrganizer.setBorderPainted(false);
        btnMaterialsOrganizer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaterialsOrganizer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMaterialsOrganizer.setIconTextGap(16);
        btnMaterialsOrganizer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaterialsOrganizerMouseClicked(evt);
            }
        });
        btnMaterialsOrganizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialsOrganizerActionPerformed(evt);
            }
        });

        btnUserProfile.setBackground(new java.awt.Color(0, 153, 153));
        btnUserProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUserProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnUserProfile.setText("User Profile");
        btnUserProfile.setBorder(null);
        btnUserProfile.setBorderPainted(false);
        btnUserProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserProfile.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUserProfile.setIconTextGap(13);
        btnUserProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserProfileMouseClicked(evt);
            }
        });
        btnUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserProfileActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(0, 153, 153));
        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Reports");
        btnReports.setToolTipText("Back to Inventory Table");
        btnReports.setBorder(null);
        btnReports.setBorderPainted(false);
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnReports.setIconTextGap(16);
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportsMouseClicked(evt);
            }
        });
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnInventory1.setBackground(new java.awt.Color(0, 153, 153));
        btnInventory1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInventory1.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory1.setText("Inventory");
        btnInventory1.setToolTipText("Back to Inventory Table");
        btnInventory1.setBorder(null);
        btnInventory1.setBorderPainted(false);
        btnInventory1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventory1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnInventory1.setIconTextGap(16);
        btnInventory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventory1MouseClicked(evt);
            }
        });
        btnInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventory1ActionPerformed(evt);
            }
        });

        btnAgenda1.setBackground(new java.awt.Color(0, 153, 153));
        btnAgenda1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgenda1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgenda1.setText("Agenda");
        btnAgenda1.setToolTipText("Back to Inventory Table");
        btnAgenda1.setBorder(null);
        btnAgenda1.setBorderPainted(false);
        btnAgenda1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgenda1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAgenda1.setIconTextGap(16);
        btnAgenda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgenda1MouseClicked(evt);
            }
        });
        btnAgenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenda1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaterialsOrganizer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInventory1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgenda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMaterialsOrganizer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HELP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserProfileActionPerformed
        initHelpUserProfile();
    }//GEN-LAST:event_btnUserProfileActionPerformed

    private void btnUserProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserProfileMouseClicked
         initHelpUserProfile();
    }//GEN-LAST:event_btnUserProfileMouseClicked

    private void btnMaterialsOrganizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialsOrganizerActionPerformed
        initHelpMaterialsOrganizer();
    }//GEN-LAST:event_btnMaterialsOrganizerActionPerformed

    private void btnMaterialsOrganizerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialsOrganizerMouseClicked
        initHelpMaterialsOrganizer();
    }//GEN-LAST:event_btnMaterialsOrganizerMouseClicked

    private void btnReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseClicked
       initPnlHelpReports();
    }//GEN-LAST:event_btnReportsMouseClicked

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        initPnlHelpReports();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnInventory1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventory1MouseClicked
        initPnlHelpInventory();
    }//GEN-LAST:event_btnInventory1MouseClicked

    private void btnInventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventory1ActionPerformed
       initPnlHelpInventory();
    }//GEN-LAST:event_btnInventory1ActionPerformed

    private void btnAgenda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgenda1MouseClicked
        initPnlHelpAgenda();
    }//GEN-LAST:event_btnAgenda1MouseClicked

    private void btnAgenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenda1ActionPerformed
        initPnlHelpAgenda();
    }//GEN-LAST:event_btnAgenda1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgenda1;
    public javax.swing.JButton btnInventory1;
    public javax.swing.JButton btnMaterialsOrganizer;
    public javax.swing.JButton btnReports;
    private javax.swing.JButton btnUserProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
