package ec.edu.espe.ehamanagement.view;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class PnlHelpAgenda extends javax.swing.JPanel {

    public PnlHelpAgenda() {
        initComponents();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupProducts = new javax.swing.ButtonGroup();
        btnGroupSearch = new javax.swing.ButtonGroup();
        pnlContent = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        lblContent1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblContent2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        lblContent3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        lblContent4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        lblContent5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTableTitle.setText("Agenda");

        lblContent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent.setText("Añadir un nuevo Pedido");
        lblContent.setAlignmentX(0.5F);

        lblContent1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent1.setText("Acceder a Agenda de Pedidos");
        lblContent1.setAlignmentX(0.5F);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Ubicarse en la barra superior de navegación. \n2. Ingresar en el menú “Actions”. \n3. Dar click en  la opcion “Agenda”. ");
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Ubicarse en la opción Add product, que se \nencuentra en la parte izquierda de la ventana. \n2. Dar click en Add producto \n3. Llenar los siguientes campos:  \n   Product’s Name (Nombre del producto)  \n  Quantity: Units (Cantidad: Unidades) \n  Working time: Hours (Tiempo de trabajo: Horas) \n  Description(Descripcion) \n4. Seleccionar de la lista desplegable uno de \nlos materiales que componen el producto \n5. Ingresar la cantidad del material  \n6. Dar click en Add \n7. Se observará los materiales que se ingresan \nel recuadro purpura de la parte inferior de la ventana \n8. Para ingresar varios materiales repetir el paso \n7), 8) y 9) \n9. Para eliminar un material no deseado: \n    9.1 Seleccionar el material a eliminar  \n    9.2 Dar click en Delete \n10. Dar click en Save para guardar el producto  \n11. En la ventana emergente preguntará: Are \nyou sure you want to save this producto? \n(¿Estás seguro de que quieres guardar este producto?). \n12. Dar clik en yes \n13. En la ventana emergente saldrá: Your \nchanges have been successfully saved! \n(¡Sus cambios han sido guardados con éxito!) \n14. Dar click en Ok  ");
        jTextArea2.setFocusable(false);
        jTextArea2.setOpaque(false);
        jScrollPane3.setViewportView(jTextArea2);

        lblContent2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent2.setText("Organizar Pedidos");
        lblContent2.setAlignmentX(0.5F);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("1. Ubicarse en la pestaña derecha “All Orders”. \n2.Seleccionar  entre las opciones \n“All Order”: Muestra todos los pedidos \nentregados y por entregar\n“Peding Orders”: Muestra los pedidos que no \nhan sido entregados\n“Delivered Orders”: Muestra los pedidos entregados\nDe esta manera se puede navegar entre las \ndistintas pestañas de las ordenes. ");
        jTextArea3.setFocusable(false);
        jTextArea3.setOpaque(false);
        jScrollPane4.setViewportView(jTextArea3);

        lblContent3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent3.setText("Buscar un Pedido");
        lblContent3.setAlignmentX(0.5F);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("1. Ubicarse en la parte inferior de la ventana \ndel aplicativo \n2. Seleccionar el tipo de búsqueda  \nA. Dar click en By ID \n      a. Ingresar el ID del producto \n      b. Dar click en Search \n      c. Se mostrará los detalles del producto encontrado  \nB. Dar click en By Name \n     a. Ingresar el nombre del producto \n     b. Dar click en Search \n    c. Se mostrará los detalles del producto encontrado  ");
        jTextArea4.setFocusable(false);
        jTextArea4.setOpaque(false);
        jScrollPane5.setViewportView(jTextArea4);

        lblContent4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent4.setText("Actualizar Productos");
        lblContent4.setAlignmentX(0.5F);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("1. Una vez buscado el pedido que se desea, \nel aplicativo nos muestra la opción de Actualizar el pedido\n2. Para editar una orden se debe cambiar\nlos datos que se muestra de una orden buscada. \n3. Cuando ya se haya cambiado los datos dar click \nen el botón“Update”. \n4. En la ventana emergente preguntará: Are you \nsure you want to update this order?\n (¿Estás seguro de que quieres actualizar este pedido?). \n5.. Dar clik en yes ");
        jTextArea5.setFocusable(false);
        jTextArea5.setOpaque(false);
        jScrollPane6.setViewportView(jTextArea5);

        lblContent5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent5.setText("Eliminar Pedidos");
        lblContent5.setAlignmentX(0.5F);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("1. Realizar el proceso de búsqueda \n2. Ubicarse en la opción Delete, que se encuentra \nen la parte inferior derecha de la venta del aplicativo \n3. Dar click en Delete \n4. En la ventana emergente preguntará: Are you sure \nyou want to delete this order? \n(¿Estás seguro de que quieres eliminar este pedido?). \n5. Dar clik en yes \n6. En la ventana emergente saldrá: Order deleted \nsuccessfully! (¡Pedido eliminado con exito!) \n7. Dar click en Ok ");
        jTextArea6.setFocusable(false);
        jTextArea6.setOpaque(false);
        jScrollPane7.setViewportView(jTextArea6);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTableTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContentLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlContentLayout.createSequentialGroup()
                                                .addComponent(lblContent1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblContent, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlContentLayout.createSequentialGroup()
                                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnlContentLayout.createSequentialGroup()
                                        .addComponent(lblContent2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlContentLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblContent3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                                        .addComponent(lblContent4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblContent5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContent1)
                    .addComponent(lblContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContent2)
                    .addComponent(lblContent3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContent4)
                    .addComponent(lblContent5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupSearch;
    private javax.swing.ButtonGroup btnGrupProducts;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblContent1;
    private javax.swing.JLabel lblContent2;
    private javax.swing.JLabel lblContent3;
    private javax.swing.JLabel lblContent4;
    private javax.swing.JLabel lblContent5;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
