package ec.edu.espe.ehamanagement.view;

/**
 *
 * @author Jairo Bonilla, Gaman GeekLords, DCCO-ESPE
 */
public class PnlHelpReports extends javax.swing.JPanel {

    public PnlHelpReports() {
        initComponents();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupProducts = new javax.swing.ButtonGroup();
        btnGroupSearch = new javax.swing.ButtonGroup();
        pnlContent = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        lblContent1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblContent2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        lblContent4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTableTitle.setText("Reports");

        lblContent1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent1.setText("Generar un Reporte General");
        lblContent1.setAlignmentX(0.5F);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ubicarse en la barra superior de navegación. \nIngresar en el menú “Actions”. \nDar click en  la opcion “Reports”. \nSe abrirá un submenú donde se puede escoger entre reporte general, reporte de inventario y reporte de agenda. \nDar click en la opción “General”. \nSe abrirá una pestaña nueva donde se puede vizualizar los reportes generales del inventario y la agenda. \nEn la parte inferior de la pestaña se puede visualizar dos botones. \nSi se desea imprimir el reporte generado, dar click en el botón “Print”. \nEl aplicativo muestra una pestaña para imprimir. \nSi se quiere regresar a la pestaña inicial, dar click en el botón ”Back”. \nEl aplicativo regresa a la seccion inicial. ");
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        lblContent2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent2.setText("Generar un Reporte de Inventario");
        lblContent2.setAlignmentX(0.5F);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Ubicarse en la barra superior de navegación. \nIngresar en el menú “Actions”. \nDar click en  la opcion “Reports”. \nSe abrirá un submenú donde se puede escoger entre reporte general, reporte de inventario y reporte de agenda. \nDar click en la opción “Inventory”. \nSe abrirá un submenú con opciones de Stock y Shortage. \nSi se escoge “Stock”. \n\tSe abrirá una pestaña nueva donde se puede vizualizar el reporte de inventario en stock. \n\tEn la parte inferior de la pestaña se puede visualizar dos botones. \n\tSi se desea imprimir el reporte generado, dar click en el botón “Print”. \n\tEl aplicativo muestra una pestaña para imprimir. \n\tSi se quiere regresar a la pestaña inicial, dar click en el botón ”Back”. \n\tEl aplicativo regresa a la seccion inicial. \nSi se escoge “Shortage” \n\tSe abrirá una pestaña nueva donde se puede vizualizar el reporte de inventario que esta en escasez. \n\tEn la parte inferior de la pestaña se puede visualizar dos botones. \n\tSi se desea imprimir el reporte generado, dar click en el botón “Print”. \n\tEl aplicativo muestra una pestaña para imprimir. \n\tSi se quiere regresar a la pestaña inicial, dar click en el botón ”Back”. \n\tEl aplicativo regresa a la seccion inicial. ");
        jTextArea3.setFocusable(false);
        jTextArea3.setOpaque(false);
        jScrollPane4.setViewportView(jTextArea3);

        lblContent4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContent4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContent4.setText("Generar un Reporte de Agenda");
        lblContent4.setAlignmentX(0.5F);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Ubicarse en la barra superior de navegación. \nIngresar en el menú “Actions”.\nDar click en  la opcion “Reports”. \nSe abrirá un submenú donde se puede escoger entre reporte general, reporte de inventario y reporte de agenda. \nDar click en la opción “Agenda”. \nSe abrirá un submenú con opciones de Completed y Pending. \nSi se escoge “Completed”. \n\tSe abrirá una pestaña nueva donde se puede vizualizar el reporte de la agenda donde estan las ordenes completas. \n\tEn la parte inferior de la pestaña se puede visualizar dos botones. \n\tSi se desea imprimir el reporte generado, dar click en el botón “Print”. \n\tEl aplicativo muestra una pestaña para imprimir. \n\tSi se quiere regresar a la pestaña inicial, dar click en el botón ”Back”. \n\tEl aplicativo regresa a la seccion inicial.\nSi se escoge “Pending” \n\tSe abrirá una pestaña nueva donde se puede vizualizar el reporte de la agenda donde estan las ordenes pendientes. \t\n\tEn la parte inferior de la pestaña se puede visualizar dos botones. \n\tSi se desea imprimir el reporte generado, dar click en el botón “Print”. \n\tEl aplicativo muestra una pestaña para imprimir. \n\tSi se quiere regresar a la pestaña inicial, dar click en el botón ”Back”. \n\tEl aplicativo regresa a la seccion inicial.");
        jTextArea5.setFocusable(false);
        jTextArea5.setOpaque(false);
        jScrollPane6.setViewportView(jTextArea5);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContent2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblContent1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                                    .addComponent(lblContent4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6))))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(lblTableTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContent2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContent4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupSearch;
    private javax.swing.ButtonGroup btnGrupProducts;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JLabel lblContent1;
    private javax.swing.JLabel lblContent2;
    private javax.swing.JLabel lblContent4;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
